version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: api-solid-pg
    environment:
      POSTGRES_DB: api-solid
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker123
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
